apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-app.fullname" . }}-configmap
data:
  {{- range $key, $value := .Values.app.config }}
  {{ $key | upper }}: "{{ $value }}"
  {{- end }}
